site_name: Scientific Computing for Physics Students
site_url: https://niklai99.github.io/ScientificComputing4Physics
repo_name: niklai99/ScientificComputing4Physics
repo_url: https://github.com/niklai99/ScientificComputing4Physics
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Task 1: 
    - "Docker installation and AlmaLinux9 setup": task1/install_docker.md
    - "AlmaLinux9 setup for Python and C/C++ development": task1/custom_docker.md
    - "Testing the AlmaLinux9 container with Python and C/C++": task1/test_py_cpp.md
  - Task 2:
    - "Introduction to Task 2": task2/intro.md
    - "Vector Sum": task2/vector_sum.md
    - "Matrix Multiplication": task2/matrix_mult.md
    - "Questions regarding Task 2": task2/questions.md
  - Task 3:
    - "Introduction to Task 3": task3/intro.md
    - "Docker installation and setup": task3/docker.md
    - "Building the project": task3/build.md
    - "Code documentation": 
      - "Code overview": task3/code_overview.md
      - "File I/O (text, binary and HDF5)": task3/vector_io.md
      - "Vector sum implementations": task3/vector_sum.md
  - Task 4:
    - "Introduction to Task 4": task4/intro.md
    - "Docker installation and setup": task4/docker.md
    - "Building the project": task4/build.md
    - "Code documentation":
      - "Code overview": task4/code_overview.md
      - "Sampling and Data I/O": task4/sampling.md
      - "Trapezoidal and Simpson integration methods": task4/integration.md
      - "Romberg integration method": task4/romberg.md
      - "Comparison with Python": task4/python.md
      - "Results and discussion": task4/results.md
  - Task 5:
    - "Introduction to Task 5": task5/intro.md
    - "Docker installation and setup": task5/docker.md
    - "Building the project": task5/build.md
    - "Task 5a: summation methods":
      - "Code overview": task5/summation_overview.md
      - "Naive and GSL summation methods": task5/for_gsl_summator.md
      - "Pairwise summation method": task5/pairwise_summator.md
      - "Kahan summation method": task5/kahan_summator.md
      - "Neumaier summation method": task5/neumaier_summator.md
    - "Task 5b: daxpy with random vectors":
      - "Code overview": task5/daxpy_overview.md
  - Task 6:
    - "Introduction to Task 6": task6/intro.md
    - "Docker installation and setup": task6/docker.md
    - "Building the project": task6/build.md
    - "Code documentation":
      - "Code overview": task6/code_overview.md
      - "Complex-to-complex FFT implementation": task6/c2c.md
      - "Real-to-complex FFT implementation": task6/r2c.md
      - "Reconstructing the full complex matrix from the half-spectrum": task6/bonus.md
  - Task 7:
    - "Introduction to Task 7": task7/intro.md
    - "Docker installation and setup": task7/docker.md
    - "Building the project": task7/build.md
  - Task 8:
    - "Introduction to Task 8": task8/intro.md
    - "Docker installation and setup": task8/docker.md
    - "Building the project": task8/build.md
    - "Code documentation":
      - "Code overview": task8/code_overview.md

  - Task 9:
    - "Introduction to Task 9": task9/intro.md
    - "Docker installation and setup": task9/docker.md
    - "Building the project": task9/build.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png

  icon:
    repo: fontawesome/brands/github

  palette: 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

  features:
      - content.code.copy
      - content.tabs.link
      - navigation.footer
      - navigation.indexes
      - navigation.expand
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.sections
      - search.highlight
      - search.suggest
      - toc.follow

      
  # custom_dir: docs/overrides

plugins:
  - search

extra:
  generator: false

extra_css:
  - "stylesheets/mystyle.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  # - pymdownx.blocks.details
  - admonition