site_name: Scientific Computing for Physics Students
repo_name: GitHub
repo_url: https://github.com/niklai99/ScientificComputing4Physics
# edit_uri: main/docs

nav:
  - Home: index.md
  - Task 1: 
    - Docker installation and AlmaLinux9 setup: task1/install_docker.md
    - AlmaLinux9 setup for Python and C/C++ development: task1/custom_docker.md
    - Testing the AlmaLinux9 container with Python and C/C++: task1/test_py_cpp.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  custom_dir: docs/overrides
  features:
      - content.code.copy
      - navigation.footer
      - navigation.indexes
      - navigation.expand
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - search.highlight
      - search.suggest
      - toc.follow

plugins:
    - search

extra_css:
  - "mystyle.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  # - callouts
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.blocks.details
  - admonition