input:
  vector_x: "./data/input/vector_N10_x.txt"
  vector_y: "./data/input/vector_N10_y.txt"
  N: 10
  a: 3.0
output:
  path: "./data/output"
  prefix: "result"
  format: "dat"  # Options: "dat", "txt", "h5" 
implementation: "gsl"  # Options: "default", "gsl"
